### ISSUE TITLE
providing an efficient data structure for the languages  array-Map

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#18]
Now all language has a array and placeholder[x] when we have many languages, it becomes really messy.
Another problem is that there many languages that have symbols that seen only when shift pressed.
Also, I feel that the useState for placeholder is unnecessary.
So, I would like to have another file that have Map that its key will be the language's name and the data for each item will be array of object that will keep for each char the regualr char and the shift char and also the placeholder.
And each component that need it(screen and keyboard) will get the language as a prop and import the Map for taking the fit data.

**Comment by AtharvaMutsaddi** [comment]
I would like to work on this issue. Will a JSON file mapping be okay? And I don't know many of the languages listed here apart from English, so can I keep some dummy characters for shift characters?
