### ISSUE TITLE
Optimizing the code and remove unnecessary useState-isUndo and isRedo

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#19]
Currently, we have two unnecessary useState, Also the redoStuck is not inside the function virtualKeyboard and i's not profession.
I want to arrange the code and remove this unnecessary useState. My goal that the code will be the most clean and effecient.
Maybe we can use seprate stuck for all the operations and the text will be in an string.
Please think how to implement this.
Good Luck!

**Comment by chavi362** [comment]
@kishoreravi24 . can you please look on this issue?

**Comment by kishoreravi24** [comment]
Please assign this to me

**Comment by chavi362** [comment]
Thank you so much!
If you have any gestion or suggestion please tell me
Good Luck!

**Comment by chavi362** [comment]
Closed as completed
