### ISSUE TITLE
Adding support for another languages 

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#3]
This task is both straightforward and enjoyable! Follow these simple steps to add your language to the Virtual Keyboard:

    Navigate to langugeData.js and find the langugeData array.

    Add all the necessary data for your language, including its name, translated name, placeholder, etc.
    (The shift array should be the characters the user have when he clicks shift)
    Please note to add the characters array in the order they are in the real keyboard)

    Run the application and verify that everything works seamlessly with the new language.

    Don't forget to update the README file to include information about the newly added language.

Good luck, and thank you for contributing to the Virtual Keyboard project! If you encounter any issues or have questions, feel free to reach out. Happy coding!

**Comment by chavi362** [comment]
This is an explanation how toadd another language:
in VirtualKeyBoard.jsx you have to edit the placeholders array her:const [isEmojiActive, setIsEmojiActive] = useState(false);
  const placeholders = [
    "הקלד כאן",
    "type here",
    "أكتب هنا",
    "друкуйте тут",
    "напечатайте здесь",
  ];
  and add suitable placeholders for the new languege.
then edit the switch in changeLanguage to support the new langueges.
Also update in KeyBoardLanguage.jsx  function handleChange  and the select tag.
Good Luck!
Please star the repository!

**Comment by stefan5441** [comment]
Hello, I would love to add my native language (Macedonian). Can I do that please? :D Thanks

**Comment by sanjeevs9** [comment]
Hello, i would like to add Hindi language. Can i go for it ? Thanks :)

**Comment by chavi362** [comment]
Of course @sanjeevs9 , Please follow the steps above and don't forget to give the repository a star and share it with your friends!
