### ISSUE TITLE
An extension of the emoji keyboard

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#30]
adding to the emojis keyboard more emojis and dividing them to categories such us: people, food,activities, symboles, whatever.
Then adding the option to chose  which category to use and adding an option for search.
 I want that it would be the same idea to windows emojis(when you type windows+;)  
If you have more questions, please let me know.
Good Luck 🤞

**Comment by chavi362** [comment]
@Michalw101 how are you? 😉😉
Would you like to work on this?

**Comment by jackl92** [comment]
if no one else is I'd like to work on this please 
I have an idea in mind already

**Comment by Michalw101** [comment]
Go for it :)
