### ISSUE TITLE
the user can delete the px

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#31]
In the font sie selector the user can change the text box and delete the px.
Mabey you can change it to nummary up down or select so the user can't change the px.
I want that it will be like the option to choose font size in Microsoft Word.

**Comment by Sky-De** [comment]
@chavi362 hi there, i would like to fix this problem, please assign this to me
Thanks

**Comment by chavi362** [comment]
Thank you! I'm happy to see you here.
Please star the repository and share it

**Comment by chavi362** [comment]
@Sky-De how is your work?

**Comment by chavi362** [comment]
@Sky-De how are you?
Do you still work on it?

**Comment by Jcruz525** [comment]
Hello @chavi362, I would like to try to fix this bug for you!

**Comment by chavi362** [comment]
Thank @Jcruz525
