### ISSUE TITLE
aadiong suitable text before delete all

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#32]
Before delete all the virtual keyboard asks the user to confirm that he want to delete all the text.
provide suitable text and you may style it.

**Comment by AnviJamkhande** [comment]
hey i saw that this issue is open and i would like to work on it. Would you assign it to me

**Comment by AnviJamkhande** [comment]
if you like my design idea, can i apply the same modal on all your alert popups? eg. when copy icon is pressed and while switching languages. please let me know so i can raise that issue.

**Comment by chavi362** [comment]
@AnviJamkhande , you can open another issue for this and work on it, I would be very happy!!!
