### ISSUE TITLE
Changing the existing Redux code to use Redux Toolkit

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#42]
Changing the existing Redux code to use Redux Toolkit is not particularly difficult and can often result in cleaner and more concise code. Redux Toolkit is designed to simplify common Redux patterns and reduce boilerplate.

**Comment by Manmit124** [comment]
Can you assign this issue to me?

**Comment by chavi362** [comment]
@Manmit124 , thank you for working on it! I'm looking forward for your PR because I need this for my next workout!
If you have any questions please let me know!
Note that the redux now used  for changing thecolor of the buttons in the virtual keyboard e=when clicking on the phizical one in the computer

**Comment by Manmit124** [comment]
@chavi362  can u review it?
