### ISSUE TITLE
When hovering on one of the special buttons an explaining text will apear

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#52]
When hovering redo appear redo and paste- paste, etc.

**Comment by chavi362** [comment]
Would you like to work on this?

**Comment by tiago1820** [comment]
Yes.

**Comment by tiago1820** [comment]
Was this what you wanted?

[issue: 52](https://www.youtube.com/watch?v=ve-QV4zN7sE)

**Comment by chavi362** [comment]
Exactly!!!
SO nice!!

‫בתאריך יום ד׳, 27 בדצמ׳ 2023 ב-22:37 מאת ‪Tiago de Oliveira‬‏ <‪
***@***.***‬‏>:‬

**Comment by tiago1820** [comment]
Internationalization is working for the following languages: English, Spanish and Portuguese.
[See here](https://virtual-keyboard-git-button-description-tiago1820.vercel.app/)

I can try to do it in the other languages, if I make a mistake on any word, you correct me.

I still need to update the project structure in the README file.

When everything is ready, I will do the PR.

**Comment by chavi362** [comment]
Thanks! I'm waiting forward to see it

‫בתאריך יום ה׳, 28 בדצמ׳ 2023 ב-19:58 מאת ‪Tiago de Oliveira‬‏ <‪
***@***.***‬‏>:‬
