### ISSUE TITLE
Duplicate emojis

### ISSUE THREAD

**Issue by tiago1820** [chavi362/virtual-keyboard#58]
Hello!

I found two duplicate emojis.

![emoji](https://github.com/chavi362/virtual-keyboard/assets/14056202/ee69b750-2bb1-4786-9ffc-5276fd760cf4)

Do you want me to remove it?

**Comment by chavi362** [comment]
Of course you can, but please support another emoji instead of it, so it will be symetric, may you want take #30 ?

**Comment by Michalw101** [comment]
I would like to do this! please assign it to meeeeeeeee
