### ISSUE TITLE
update the image of the keyboard in the readme-first-timers-contributors-only

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#61]
Please update the snapshot in the Demo to the current version of the keyboard

**Comment by maryjonah** [comment]
Hi @chavi362, I have raised a PR for this issue [ Update image of Demo section in README.md](https://github.com/chavi362/virtual-keyboard/pull/67)

**Comment by chavi362** [comment]
Current now, the style changes so the image is not up to date.
First timer contributor can update this
