### ISSUE TITLE
shift button doesn't work

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#62]
When you click shift you get an error

**Comment by Jcruz525** [comment]
I would like to resolve this issue please!

**Comment by chavi362** [comment]
Good Luck!
If you have questions please let me know

‫בתאריך יום ג׳, 2 בינו׳ 2024 ב-18:24 מאת ‪Johnny Cruz III‬‏ <‪
***@***.***‬‏>:‬

**Comment by chavi362** [comment]
Thanks @Jcruz525
