### ISSUE TITLE
Design the style selector components

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#66]
Note that the lower all and upper all aren't in the same size . Also the underline button is alone without anything button and all of that don't look good

**Comment by Sabbirfeni** [comment]
Hi Chavi,

I have checked out the keyboard. I am interested on work on this project. Please assign this issue to me.

Best,
Shabbir

**Comment by Sabbirfeni** [comment]
Thank you, I will get down to work once I get the chance.

**Comment by chavi362** [comment]
@Sabbirfeni how is your work?
