### ISSUE TITLE
Feature Request: Text Alignment Option in Style Selector Component

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#73]
Currently, the Style Selector component provides a great set of options for customizing text style. However, an additional enhancement can be made to include text alignment options such as left, right, and center.
Add something like that 
![image](https://github.com/chavi362/virtual-keyboard/assets/140444217/0ec99e81-ca86-441b-b4bb-ec0cbc9996b2)
that when hovering will intraduct also the two other options and when clicking on this the text-aligment will change.
You also will have to update the letterStyle class.
Good Luck

**Comment by Jcruz525** [comment]
I would like to give this a shot!

**Comment by chavi362** [comment]
@Jcruz525  do you have time to complete it?
