### ISSUE TITLE
Copy and paste buttons

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#9]
Adding in specialbuttons.jsx a button of copy and a button of paste
When clicking copy it will copy all the text so you can paste or in the screen or in another place in the computer.
When clicking paste it will paste the text you copy or a text you copy from another place.
Good Luck!!!

**Comment by chavi362** [comment]
close as #17

**Comment by atilagulers** [comment]
![0](https://github.com/chavi362/virtual-keyboard/assets/128936466/352c2dbb-b50a-481c-b677-7bf05019bbf8)
![1](https://github.com/chavi362/virtual-keyboard/assets/128936466/ee4261c2-3ec0-43a2-b615-ac5fa6207544)
![2](https://github.com/chavi362/virtual-keyboard/assets/128936466/65679483-1157-4e1d-af8a-36b513b10a52)


![case](https://github.com/chavi362/virtual-keyboard/assets/128936466/88807697-8c9b-482d-9dba-a62f08eb93dd)
![func](https://github.com/chavi362/virtual-keyboard/assets/128936466/cc5dab58-6390-40b6-9a36-03f69d7d0557)

maybe something like this? we can navigate buttons right now by focusing

**Comment by atilagulers** [comment]
also if you want we can add all buttons, inputs, text areas etc.. 

if we select from document
