### ISSUE TITLE
make the buttons more user friendly/accessible and modern 

### ISSUE THREAD

**Issue by jackl92** [chavi362/virtual-keyboard#91]
hey, I'm new to open source projects so I apologise if I'm doing anything wrong. I noticed all buttons are using default styling, in some places they blend in making it harder for people with sight problems to see. the "upper" all button also has a bug that makes the button and colour selector bigger. also if possible could I also modify hover effects and active effects.

**Comment by chavi362** [comment]
Oh, you do everything well!
zNote that #84 pr works om style, so let's wait that cydanel will complete and we'll see what from the issue solved by this pr.
Then, you'll can work on this

**Comment by jackl92** [comment]
my bad. shall I leave this issue open until then just incase there are further changes that need to be done? or close it and make another one in the future?

**Comment by chavi362** [comment]
Of course leave it open!!
I really don't know if the layout issue should solve all the bugs
And I very much want to see you as part of our contributors!
Let's wait for this pr, then you'll can start working!


‫בתאריך יום ד׳, 24 בינו׳ 2024 ב-20:13 מאת ‪jackl92‬‏ <‪
***@***.***‬‏>:‬

**Comment by jackl92** [comment]
thank you!
either way I'll contribute some way if everything does get sorted with the previous issue 
I'll keep an eye out

**Comment by chavi362** [comment]
Please look on the keyboard now and tell me if you see something in the buttons that needs improvement.

**Comment by jackl92** [comment]
the keyboards looking perfect I could change the convert to pdf and copy/paste etc and emoji buttons
