### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by tiago1820** [chavi362/virtual-keyboard#97]
Hello @chavi362 , how are you?

What do you think if I make a Rest API to connect to the keyboard and store the characters and emojis in the database?
In the future we may also store custom user configurations(colors, fonts) and data.

**Comment by chavi362** [comment]
Oh, I'm happy to hear from you again !
I'm not sure it is good, because we don't have so much data, and making
ApI's requests can take time so the application will be slower.
What do you think?

‫בתאריך יום א׳, 28 בינו׳ 2024 ב-6:19 מאת ‪Tiago de Oliveira‬‏ <‪
***@***.***‬‏>:‬

**Comment by tiago1820** [comment]
The keyboard can work fine 100% on the frontend. The truth is that there is not much need for a backend. It would be more of an experiment.

**Comment by chavi362** [comment]
Would you like maybe to pick up another issue?
